// Generated by scripts/generate-web-schema.py; do not edit manually.
window.SBD_WEB_SCHEMA = {
  "generatedFrom": [
    "lib/protocols.sh",
    "lib/providers_base_protocol.sh",
    "lib/cli_args.sh",
    "lib/providers_base_runtime.sh"
  ],
  "providers": [
    "vps",
    "serv00"
  ],
  "profiles": [
    "lite",
    "full"
  ],
  "engines": [
    "sing-box",
    "xray"
  ],
  "protocols": [
    "vless-reality",
    "vless-xhttp",
    "vless-ws",
    "shadowsocks-2022",
    "naive",
    "hysteria2",
    "tuic"
  ],
  "protocolHints": {
    "vless-reality": "default secure choice",
    "vless-xhttp": "requires xray runtime",
    "vless-ws": "simple ws profile",
    "shadowsocks-2022": "password management required",
    "naive": "requires user-controlled domain and trusted certificate",
    "hysteria2": "requires user-controlled domain and trusted certificate; udp heavy at high throughput",
    "tuic": "requires user-controlled domain and trusted certificate; udp + tls cert overhead"
  },
  "engineSupport": {
    "sing-box": [
      "vless-reality",
      "vless-ws",
      "shadowsocks-2022",
      "naive",
      "hysteria2",
      "tuic"
    ],
    "xray": [
      "vless-reality",
      "vless-ws",
      "vless-xhttp"
    ]
  },
  "presets": {
    "reality-only": {
      "label": "reality-only",
      "engine": "sing-box",
      "profile": "lite",
      "protocols": "vless-reality",
      "requiresDomainCert": false
    },
    "reality-plus-domain": {
      "label": "reality-plus-domain",
      "engine": "sing-box",
      "profile": "full",
      "protocols": "vless-reality,hysteria2,tuic,naive",
      "requiresDomainCert": true
    },
    "full": {
      "label": "full",
      "engine": "sing-box",
      "profile": "full",
      "protocols": "vless-reality,vless-ws,shadowsocks-2022,naive,hysteria2,tuic",
      "requiresDomainCert": true
    }
  },
  "tlsModes": [
    "self-signed",
    "acme",
    "acme-auto"
  ],
  "webFrontModes": [
    "auto",
    "off",
    "nginx",
    "openresty"
  ],
  "hy2ObfsModes": [
    "off",
    "salamander"
  ],
  "routeModes": [
    "direct",
    "global-proxy",
    "cn-direct",
    "cn-proxy"
  ],
  "outboundProxyModes": [
    "direct",
    "socks",
    "http",
    "https"
  ]
};
