#!/usr/bin/env python3
"""Generate web-generator/schema.js from backend shell contract files."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def parse_array(text: str, name: str) -> list[str]:
    m = re.search(rf"{re.escape(name)}=\(\s*(.*?)\s*\)", text, re.S)
    if not m:
        raise SystemExit(f"unable to find array {name}")
    return [x.strip().strip("\"'") for x in m.group(1).splitlines() if x.strip()]


def parse_protocol_hints(text: str, protocols: list[str]) -> dict[str, str]:
    hints: dict[str, str] = {}
    for proto in protocols:
        pat = rf'{re.escape(proto)}\)\s*\n\s*echo "([^"]+)"'
        m = re.search(pat, text)
        if m:
            raw = m.group(1)
            note = raw.split("note=", 1)[1] if "note=" in raw else raw
            hints[proto] = note
    missing = [p for p in protocols if p not in hints]
    if missing:
        raise SystemExit(f"missing protocol hints: {', '.join(missing)}")
    return hints


def parse_engine_support(text: str, engine: str) -> list[str]:
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == f"{engine})":
            for inner in lines[i : i + 8]:
                m = re.search(r"([A-Za-z0-9_|-]+)\) return 0 ;;", inner)
                if m:
                    return m.group(1).split("|")
    raise SystemExit(f"unable to parse supported protocols for {engine}")


def parse_presets(text: str) -> dict[str, dict[str, str]]:
    presets = {
        "reality-only": {"label": "reality-only", "engine": "sing-box", "profile": "lite", "protocols": "vless-reality", "requiresDomainCert": False},
        "reality-plus-domain": {"label": "reality-plus-domain", "engine": "sing-box", "profile": "full", "protocols": "vless-reality,hysteria2,tuic,naive", "requiresDomainCert": True},
        "full": {"label": "full", "engine": "sing-box", "profile": "full", "protocols": "vless-reality,vless-ws,shadowsocks-2022,naive,hysteria2,tuic", "requiresDomainCert": True},
    }
    for key, expected in presets.items():
        needle = expected["protocols"]
        if needle not in text:
            raise SystemExit(f"preset protocols not found in cli_args.sh: {key} -> {needle}")
    return presets


def parse_case_modes(text: str, var: str) -> list[str]:
    idx = text.find(f'case "${{{var}:-')
    if idx < 0:
        raise SystemExit(f"unable to find case for {var}")
    block = text[idx: idx + 500]
    m = re.search(r"([a-zA-Z0-9_|-]+)\) ;;", block)
    if not m:
        raise SystemExit(f"unable to parse modes for {var}")
    return m.group(1).split("|")


def main() -> None:
    protocols_sh = read("lib/protocols.sh")
    base_protocol = read("lib/providers_base_protocol.sh")
    base_runtime = read("lib/providers_base_runtime.sh")
    cli_args = read("lib/cli_args.sh")

    protocols = parse_array(protocols_sh, "ALL_PROTOCOLS")
    schema = {
        "generatedFrom": [
            "lib/protocols.sh",
            "lib/providers_base_protocol.sh",
            "lib/cli_args.sh",
            "lib/providers_base_runtime.sh",
        ],
        "providers": ["vps", "serv00"],
        "profiles": ["lite", "full"],
        "engines": ["sing-box", "xray"],
        "protocols": protocols,
        "protocolHints": parse_protocol_hints(protocols_sh, protocols),
        "engineSupport": {
            "sing-box": parse_engine_support(base_protocol, "sing-box"),
            "xray": parse_engine_support(base_protocol, "xray"),
        },
        "presets": parse_presets(cli_args),
        "tlsModes": parse_case_modes(base_runtime, "TLS_MODE"),
        "webFrontModes": parse_case_modes(base_runtime, "WEB_FRONT_MODE"),
        "hy2ObfsModes": [m for m in parse_case_modes(base_runtime, "HY2_OBFS_MODE") if m != "gecko"],
        "routeModes": ["direct", "global-proxy", "cn-direct", "cn-proxy"],
        "outboundProxyModes": ["direct", "socks", "http", "https"],
    }

    out = ROOT / "web-generator/schema.js"
    body = "// Generated by scripts/generate-web-schema.py; do not edit manually.\n"
    body += "window.SBD_WEB_SCHEMA = " + json.dumps(schema, ensure_ascii=False, indent=2) + ";\n"
    out.write_text(body, encoding="utf-8")
    print(f"generated {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
