#!/usr/bin/env bash
# sfw-package.sh — Build SFW (Sing-box For Windows) client package
# Downloads official sing-box Windows binary and bundles with generated config
#
# Usage:
#   bash sfw-package.sh [--output DIR] [--config PATH] [--tag VERSION]
#
# Outputs: sing-box-deve-sfw-{arch}.zip in output directory

set -euo pipefail

SFW_OUTPUT_DIR="${SFW_OUTPUT_DIR:-.}"
SFW_CONFIG_FILE=""
SFW_TAG="${SFW_TAG:-latest}"
SFW_REPO="SagerNet/sing-box"

log() { printf '[SFW] %s\n' "$*"; }

fetch_latest_tag() {
  curl -fsSL "https://api.github.com/repos/${SFW_REPO}/releases/latest" | \
    grep -oP '"tag_name":\s*"\K[^"]+' | head -n1
}

build_sfw_package() {
  local arch="$1"
  local tag="$2"
  local config="$3"
  local outdir="$4"

  local asset_name="sing-box-${tag#v}-windows-${arch}"
  local zip_url="https://github.com/${SFW_REPO}/releases/download/${tag}/${asset_name}.zip"

  local tmpdir
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "$tmpdir"' EXIT

  log "Downloading ${asset_name}.zip ..."
  curl -fsSL "$zip_url" -o "${tmpdir}/sfw.zip" || {
    log "ERROR: Failed to download ${zip_url}"
    return 1
  }

  log "Extracting..."
  unzip -q "${tmpdir}/sfw.zip" -d "${tmpdir}/sfw"

  # Find the sing-box.exe
  local exe
  exe="$(find "${tmpdir}/sfw" -name 'sing-box.exe' -type f | head -n1)"
  if [[ -z "$exe" ]]; then
    log "ERROR: sing-box.exe not found in archive"
    return 1
  fi

  local pkg_dir="${tmpdir}/sing-box-deve-sfw"
  mkdir -p "$pkg_dir"

  # Copy binary
  cp "$exe" "$pkg_dir/sing-box.exe"

  # Copy config if provided
  if [[ -n "$config" && -f "$config" ]]; then
    cp "$config" "$pkg_dir/config.json"
    log "Bundled config: ${config}"
  fi

  # Create launcher script
  cat > "$pkg_dir/start.bat" <<'BAT'
@echo off
echo Starting sing-box-deve client...
sing-box.exe run -c config.json
pause
BAT

  # Create README
  cat > "$pkg_dir/README.txt" <<TXT
sing-box-deve SFW Client Package
=================================
1. Edit config.json with your server details
2. Double-click start.bat to run
3. Or run: sing-box.exe run -c config.json

Generated by sing-box-deve
TXT

  # Package
  mkdir -p "$outdir"
  local out_zip="${outdir}/sing-box-deve-sfw-${arch}.zip"
  (cd "${tmpdir}" && zip -rq "$out_zip" "sing-box-deve-sfw/")

  log "Package created: ${out_zip}"
}

# ── CLI ───────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)  SFW_OUTPUT_DIR="$2"; shift 2 ;;
    --config)  SFW_CONFIG_FILE="$2"; shift 2 ;;
    --tag)     SFW_TAG="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: bash sfw-package.sh [--output DIR] [--config PATH] [--tag VERSION]"
      exit 0
      ;;
    *) shift ;;
  esac
done

if [[ "$SFW_TAG" == "latest" ]]; then
  log "Fetching latest release tag..."
  SFW_TAG="$(fetch_latest_tag)"
  [[ -n "$SFW_TAG" ]] || { log "ERROR: Cannot fetch latest tag"; exit 1; }
fi

log "Building SFW packages for tag ${SFW_TAG}"

# Try to find config from runtime
if [[ -z "$SFW_CONFIG_FILE" ]]; then
  for candidate in \
    "/etc/sing-box-deve/sfw-config.json" \
    "/opt/sing-box-deve/data/sfw-config.json" \
    "${HOME}/sing-box-deve/data/sfw-config.json"; do
    if [[ -f "$candidate" ]]; then
      SFW_CONFIG_FILE="$candidate"
      break
    fi
  done
fi

build_sfw_package "amd64" "$SFW_TAG" "$SFW_CONFIG_FILE" "$SFW_OUTPUT_DIR"
build_sfw_package "arm64" "$SFW_TAG" "$SFW_CONFIG_FILE" "$SFW_OUTPUT_DIR" || \
  log "arm64 package skipped (may not be available for this version)"

log "Done."
