#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="${ROOT_DIR}/checksums.txt"

files=(
  "sing-box-deve.sh"
  "version"
  "README.md"
  "CHANGELOG.md"
  "CONTRIBUTING.md"
  "LICENSE"
  "config.env.example"
  "lib/common.sh"
  "lib/common_base.sh"
  "lib/common_settings.sh"
  "lib/common_update.sh"
  "lib/common_context.sh"
  "lib/common_doctor.sh"
  "lib/protocols.sh"
  "lib/security.sh"
  "lib/legacy_compat.sh"
  "lib/providers.sh"
  "lib/providers_base.sh"
  "lib/providers_params.sh"
  "lib/providers_release.sh"
  "lib/providers_outbound.sh"
  "lib/providers_routing.sh"
  "lib/providers_argo.sh"
  "lib/providers_config_shared.sh"
  "lib/providers_config_singbox.sh"
  "lib/providers_config_xray.sh"
  "lib/providers_nodes.sh"
  "lib/providers_client_templates.sh"
  "lib/providers_install.sh"
  "lib/providers_serv00.sh"
  "lib/providers_sap.sh"
  "lib/providers_docker.sh"
  "lib/providers_manage.sh"
  "lib/providers_ports.sh"
  "lib/providers_config_ops.sh"
  "lib/providers_split3.sh"
  "lib/providers_jump_ports.sh"
  "lib/providers_system_tools.sh"
  "lib/providers_subscriptions.sh"
  "lib/providers_panel.sh"
  "lib/providers_doctor.sh"
  "lib/providers_uninstall.sh"
  "lib/output.sh"
  "lib/menu.sh"
  "lib/menu_base.sh"
  "lib/menu_sections.sh"
  "lib/menu_subscriptions.sh"
  "lib/menu_config_center.sh"
  "lib/menu_ops.sh"
  "lib/menu_main.sh"
  "lib/cli_args.sh"
  "lib/cli_commands.sh"
  "lib/cli_wizard.sh"
  "lib/cli_main.sh"
  "docs/README.md"
  "docs/V1-SPEC.md"
  "docs/CONVENTIONS.md"
  "docs/ACCEPTANCE-MATRIX.md"
  "docs/PANEL-TEMPLATE.md"
  "docs/REAL-WORLD-VALIDATION.md"
  "docs/Serv00.md"
  "docs/SAP.md"
  "docs/Docker.md"
  "examples/vps-lite.env"
  "examples/vps-full-argo.env"
  "examples/docker.env"
  "examples/settings.conf"
  "examples/serv00-accounts.json"
  "examples/sap-accounts.json"
  "web-generator/index.html"
  "providers/entry.sh"
  "providers/vps.sh"
  "providers/serv00.sh"
  "providers/sap.sh"
  "providers/docker.sh"
  "scripts/acceptance-matrix.sh"
  "scripts/integration-smoke.sh"
  "scripts/consistency-check.sh"
  "scripts/update-checksums.sh"
  ".github/workflows/main.yml"
  ".github/workflows/mainh.yml"
  ".github/workflows/ci.yml"
  "workers/_worker.js"
  "workers/workers_keep.js"
)

tmp="$(mktemp)"
for rel in "${files[@]}"; do
  sha256sum "${ROOT_DIR}/${rel}" | awk -v r="$rel" '{print $1 "  " r}' >> "$tmp"
done
mv "$tmp" "$OUT_FILE"
echo "Generated ${OUT_FILE}"
